version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: git config --global user.email "circleci@zakharov.com"
      - run: git config --global user.name "Circle CI"
      - run: mkdir build
      - run: cd /home/circleci/project/build
      - run: git init
      - run: git remote add origin https://github.com/ivanzakharov/docs
      - run: git pull origin build
      - run: date "+%d/%m/%y %H:%M" >> .circleci/update.log
      - run: git add .
      - run: git commit -m 'Docs update'
      - run: git push origin build
